services:
  - type: web
    name: storybote
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "source /opt/render/project/src/.venv/bin/activate && python bot.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
